#!/bin/sh
#
# $OpenBSD$

daemon="/usr/local/bin/proxgit"
daemon_user="git"
daemon_flags="web -c /etc/proxgit/app.ini"

proxgit_directory="/var/lib/proxgit"

rc_bg=YES

. /etc/rc.d/rc.subr

rc_start() {
	${rcexec} "cd ${proxgit_directory}; ${daemon} ${daemon_flags} ${_bg}"
}

rc_cmd $1
